
stages:
  - build
  - deploy

build-game:
  stage: build
  only:
    - main
  before_script:
    - git lfs install
    - git lfs pull
    - git submodule update
  script:
    - rm -rf BeamMeUpATCA/Builds/out
    - /home/deco3801/Unity/Hub/Editor/2020.3.38f1/Editor/Unity -batchmode -quit -nographics -projectPath $(pwd)/BeamMeUpATCA -executeMethod BuildScript.PreformAllBuilds BeamMeUpATCA out -serial F4-7KDF-ABM2-XUY5-Z6M8-XXXX -logFile $(pwd)/BUILDLOG.log
    - mkdir -p bin
    - mv BeamMeUpATCA/Builds/out .
    - zip -r build.zip out
  artifacts:
    paths:
      - build.zip
    expire_in: 1 Day
  
  after_script:
    - cat $(pwd)/BUILDLOG.log

deploy-nas:
  stage: deploy
  only:
    - tags
  dependencies:
    - build-game
  script:
    - cp build.zip $CI_COMMIT_TAG.zip
    - cp build.zip LATEST.zip
    - curl -T $CI_COMMIT_TAG.zip ftp://deco3801:t6FqxdT3@192.168.1.44/deco3801/
    - curl -T LATEST.zip ftp://deco3801:t6FqxdT3@192.168.1.44/deco3801/
  artifacts:
    paths:
      - $CI_COMMIT_TAG.zip
